version: '3.1'

services:
 
  php:
    image: php:8.0-apache
    volumes:
      - ./:/var/www/html
    restart: always
    ports:
      - 8080:80    
    container_name: container_app

  # db:
  #   image: mysql
  #   restart: always
  #   command: --default-authentication-plugin=mysql_native_password
  #   environment:
  #     MYSQL_ROOT_PASSWORD: 42

  # phpmyadmin:
  #   image: phpmyadmin
  #   restart: always
  #   ports:
  #     - 8080:80
  #   environment:
  #     - PMA_ARBITRARY=1